CREATE TABLE Person(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fullName varchar NOT NULL UNIQUE,
                    yearBorn int NOT NULL
)

CREATE TABLE Book(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  title varchar(100) NOT NULL,
                  authorName varchar(100) NOT NULL,
                  yearOfWriting int check (yearOfWriting > 1000 AND yearOfWriting <= 2025),
                  person_id int REFERENCES Person(id) ON DELETE SET NULL
)